# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Design By Tech
tagline:          'A Blog'
description:      'Welcome to my slice of the internet. I write about Design, Techonology, Entrepeneurship and life in general. Follow me <a href="https://twitter.com/timsitorus1" target="_blank">@timsitorus1</a>'
url:              http://hyde.getpoole.com

author:
  name:           'Timotius Sitorus'
  url:            https://twitter.com/timsitorus1

paginate:         5

# Custom vars
version:          2.0.0

github:	          https://github.com/timotius02

twitter:		  https://twitter.com/timsitorus1

linkedin:		  https://www.linkedin.com/in/timotius02
